version: 2.1

jobs:
  build_and_push:
    machine: true
    environment:
      IMAGE_NAME: subham966/olap
    steps:
      - checkout
      - run:
          name: Docker Login
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Push Docker Image
          command: docker push $IMAGE_NAME:latest
      - run:
          name: Show Built Docker Image Info
          command: |
            docker image ls | grep "$IMAGE_NAME"
            echo "Digest of built image:"
            docker inspect --format='{{index .RepoDigests 0}}' $IMAGE_NAME:latest || echo "Digest not available"

  deploy:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "Z4t6JpFL5B/DHUzX09yH/CpRh+pym4PIVwZm3NcMBa4"
      - run:
          name: Deploy OLAP to GCP VM
          command: |
            ssh -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" \<<EOF
              set -e
              echo "Logging into Docker Hub..."
              echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
              
              cd /home/prod/
              echo "Updating OLAP image version..."
              # Update image to 'latest'
              sed -i 's|image: .*|image: subham966/olap:latest|g' olap.yml

              echo "Restarting OLAP service..."
              docker compose -f olap.yml down
              docker compose -f olap.yml up -d

              echo "Verifying pulled image..."
              docker image ls | grep subham966/olap
              echo "Digest of pulled image:"
              docker inspect --format='{{index .RepoDigests 0}}' subham966/olap:latest || echo "Digest not available"
            EOF

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_push:
          filters:
            branches:
              only: [cicd-deploy]
      - deploy:
          requires:
            - build_and_push
          filters:
            branches:
              only: [cicd-deploy]
