version: 2.1

jobs:
  build_and_push:
    machine: true
    environment:
      IMAGE_NAME: subham966/olap
    steps:
      - checkout
      - run:
          name: Set Version Tag
          command: |
            echo "export VERSION_TAG=${CIRCLE_BUILD_NUM}" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Docker Login
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME:$VERSION_TAG .
      - run:
          name: Push Docker Image
          command: docker push $IMAGE_NAME:$VERSION_TAG

workflows:
  version: 2
  build_and_push_workflow:
    jobs:
      - build_and_push:
          filters:
            branches:
              only:
                - manual-trigger
                - cicd

#==============================================================================

# workflows:
#   version: 2
#   build_and_push_workflow:
#     jobs:
#       - build_and_push:
#           filters:
#             branches:
#               only:
#                 - main
#                 - staging
#                 - cicd
